project:
  type: website
  output-dir: docs
website:
  title: "CS 5805 Machine Learning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    embed-resources: true
    code-copy: true
    code-link: true
    code-tools: true
    theme:
      dark: darkly
      light: lightly
    css: styles.css

editor: visual

